name: little-joys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.20.0
    - pydantic>=2.0.0
    - python-dotenv>=0.20.0
    - httpx>=0.24.0 
    - supabase=2.15.3